version: '3.6'

services:

  nginx:
    container_name: freepik_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/freepik
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  php-fpm:
    container_name: freepik_php-fpm
    build:
      context: ./docker/php-fpm
    user: "$UID"
    volumes:
      - ./:/var/www/freepik
    depends_on:
      - php

  php:
    container_name: freepik_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    user: "$UID"
    volumes:
      - ./:/usr/src/app
    tty: true

